server:
  port: ${PORT:8070}
bs23:
  microservices: gateway,configuration-server,edge,guardian
spring:
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      client:
        registration:
          default:
            client-secret: ${CC_EDGE}
  cloud:
    loadbalancer:
      retry:
        enabled: false
    gateway:
      default-filters:
        - TokenRelay
        - RemoveRequestHeader=Cookie
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
ribbon:
  ReadTimeout: 15000
---
