spring:
  security:
    oauth2:
      client:
        registration:
          default:
            client-secret: ${CC_EMAIL}
#  mail:
#    host: ${EMAIL_HOST:smtp.gmail.com}
#    port: ${EMAIL_PORT:587}
#    username: ${EMAIL_USERNAME}
#    password: ${EMAIL_PASSWORD}
#    properties:
#      mail:
#        smtp:
#          auth: true
#          connectiontimeout: 5000
#          timeout: 5000
#          writetimeout: 500
#          starttls:
#            enable: true
  mail:
    properties:
      mail:
        smtp:
          host: mail.abbl.com
          port: 25
          username: noreply@abbl.com
          auth: false
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 500
          starttls:
            enable: false
---
