server:
  port: ${PORT:7000}
spring:
  boot:
    admin:
      ui:
        title: Guardian
        brand: Brain Sttaion 23 Guardian
  zipkin:
    baseUrl: http://172.16.229.236:9411
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST}:${eureka.instance.port}/eureka/
logging:
  level:
    org:
      springframework:
        security: DEBUG
      arun: DEBUG
