spring:
  security:
    oauth2:
      client:
        registration:
          default:
            client-secret: ${CC_SMS}
sms:
  url: http://172.16.8.132:9910/sms
  #  username: abblibank
  #  password: u>91G669
  #  sid: abbankbulk
  username: abblretail
  password: g=76H915
  sid: ABBLRetailLoan
---
